#!/usr/bin/env bash

VERSION=$1

# Create orphan branch for create tag
git checkout --orphan "tmp_build_$VERSION"

# Change nginx version in Dockerfile
cat Dockerfile | sed "s,NGINX_VERSION nginx-.*,NGINX_VERSION nginx-$VERSION," > Dockerfile.tmp
mv Dockerfile.tmp Dockerfile

# Commit Dockerfile
git add Dockerfile
git commit -m "v$VERSION"

# Git tag
git tag "v$VERSION"

# Checkout master and forget the build branch
git checkout master
git branch -D "tmp_build_$VERSION"
